version: 2.1

orbs:
  node: circleci/node@5.0.1

commands:
  install_dependencies:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.14.2'
      - run: yarn install

node_config: &node_config
  docker:
    - image: cimg/base:stable

workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production

jobs:
  build:
    <<: *node_config
    steps:
      - install_dependencies

  test:
    <<: *node_config
    steps:
      - install_dependencies
      - run:
          name: 'Compile Typescript'
          command: yarn tsc

  deploy:
    <<: *node_config
    steps:
      - install_dependencies
      - run: echo 'deploy'
